services:
  extractorw:
    build: .
    container_name: extractorw-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DOCKER_ENV=true
    env_file:
      - .env
    volumes:
      - logs:/app/logs
      - transcriptions:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - extractorw-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  logs:
    driver: local
  transcriptions:
    driver: local

networks:
  extractorw-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-extractorw
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 